return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufEnter", "VeryLazy" },
	opts = {
		highlight = { enable = true },
		indent = { enable = false },
		sync_install = false,
		auto_install = true,
		ensure_installed = {
			"asm",
			"bash",
			"c",
			"cmake",
			"cpp",
			"cuda",
			"dockerfile",
			"doxygen",
			"fortran",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"latex",
			"llvm",
			"lua",
			"make",
			"markdown",
			"mlir",
			"ninja",
			"nix",
			"python",
			"rust",
			"sql",
			"tmux",
			"toml",
			"vim",
			"yaml",
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
