return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "asm",
      "bash",
      "bibtex",
      "c",
      "cmake",
      "cpp",
      "csv",
      "cuda",
      "diff",
      "dockerfile",
      "doxygen",
      "fish",
      "html",
      "json",
      "latex",
      "llvm",
      "lua",
      "make",
      "markdown",
      "mlir",
      "ninja",
      "python",
      "regex",
      "rust",
      "sql",
      "tmux",
      "toml",
      "yaml",
      "html",
      "latex",
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
    incremental_selection = { enable = true },
    textobjects = { enable = true },
    indent = { enable = true },
  },
  cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
}
